/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Icon = string;
export type Desc = string;
export type Url = string;
/**
 * tags
 */
export type Tags = string[];
/**
 * Time stamp of event started
 */
export type StartDate = string;
/**
 * Time stamp of event ended
 */
export type EndDate = string;

export interface Event {
  name: string;
  icon?: Icon;
  desc?: Desc;
  url?: Url;
  organizationId?: string;
  tags?: Tags;
  startDate?: StartDate;
  endDate?: EndDate;
  [k: string]: unknown;
}
