/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type EventName = string;
export type EventIcon = string;
export type EventId = string;
export type BasicEvidences = BasicEvidence[];
export type UpdatedAt = string;

export interface EventAttendanceVerifiableCredential {
  "@context": string[];
  type: string[];
  id: string;
  issuer: {
    id: string;
    ethereumAddress?: string;
    [k: string]: unknown;
  };
  credentialSubject: EventAttendance;
  credentialSchema: {
    id: string;
    type: string;
  };
  issuanceDate: string;
  expirationDate?: string;
  proof?: {
    type: string;
    verificationMethod?: string;
    ethereumAddress?: string;
    created?: string;
    proofPurpose?: string;
    proofValue?: string;
    eip712?: {
      domain: {
        chainId: number;
        name: string;
        version: string;
        verifyingContract?: string;
      };
      types: {
        [k: string]: unknown;
      };
      primaryType: string;
    };
    [k: string]: unknown;
  };
  evidence?: BasicEvidences;
  credentialStatus?: {
    id: string;
    type: string;
  };
  updatedAt?: UpdatedAt;
}
export interface EventAttendance {
  id: string;
  eventName: EventName;
  eventIcon?: EventIcon;
  eventId: EventId;
  [k: string]: unknown;
}
export interface BasicEvidence {
  id: string;
  type: string[];
  verifier?: string;
  evidenceDocument?: string;
  subjectPresence?: string;
  documentPresence?: string;
  item?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
