/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type OrganizationId = string;
export type MembershipId = string;

export interface MembershipSubject {
  id: Id;
  organizationId: OrganizationId;
  membershipId: MembershipId;
  [k: string]: unknown;
}
