/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type OrganizationId = string;
export type Name = string;
export type Desc = string;
export type Icon = string;
export type CreatedAt = string;

export interface Membership {
  organizationId: OrganizationId;
  name: Name;
  desc?: Desc;
  icon?: Icon;
  createdAt?: CreatedAt;
  [k: string]: unknown;
}
