/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * paid value
 */
export type Value = string;
/**
 * paid value
 */
export type Value1 = string;
/**
 * work summary
 */
export type Summary = string;
/**
 * work detail
 */
export type Detail = string;
/**
 * work genre e.g, Dev, Design etc
 */
export type Genre = string;
/**
 * work tags
 */
export type Tags = string[];
/**
 * currently support fulltime, parttime, and onetime
 */
export type JobType = string;
/**
 * Time stamp of work started
 */
export type StartTimestamp = string;
/**
 * Time stamp of work ended
 */
export type EndTimestamp = string;
/**
 * a transaction platform if exists e.g, gitcoin
 */
export type Platform = string;
/**
 * hash value of all work descriptions(summary, detail, deliverables)
 */
export type DeliverableHash = string;
/**
 * CRDL issue date
 */
export type IssuedAt = string;
/**
 * organization Id if exist
 */
export type Organization = string;
/**
 * hash of the transaction
 */
export type TxHash = string;
/**
 * payee address
 */
export type To = string;
/**
 * payer address
 */
export type From = string;
/**
 * whether or not DID is payer
 */
export type IsPayer = boolean;
/**
 * paid value
 */
export type Value2 = string;
/**
 * paid token symbol
 */
export type TokenSymbol = string;
/**
 * paid token decimal
 */
export type TokenDecimal = number;
/**
 * fiat price at the time of the transaction
 */
export type Value3 = string;
/**
 * currently only support USD
 */
export type FiatSymbol = string;
/**
 * network id of the transaction
 */
export type NetworkId = number;
/**
 * Time stamp of transaction occurrence
 */
export type IssuedTimestamp = string;
export type RelatedAddress = string[];
export type RelatedTxHashes = string[];
/**
 * current formats are url or cid
 */
export type Format = string;
/**
 * work deliverable value(url/cid)
 */
export type Value4 = string;
export type Deliverables = DeliverableItem[];
/**
 * name or DID
 */
export type Format1 = string;
/**
 * Client Info
 */
export type Value5 = string;
/**
 * signature of holder
 */
export type HolderSig = string;
/**
 * DID of agent
 */
export type PartnerSigner = string;
/**
 * signature of partner
 */
export type PartnerSig = string;
/**
 * DID of agent
 */
export type AgentSigner = string;
/**
 * signature of agent
 */
export type AgentSig = string;
export type CreatedAt = string;
export type UpdatedAt = string;

export interface WorkCredential {
  id: string;
  subject: WorkSubject;
  signature?: Signatures;
  createdAt?: CreatedAt;
  updatedAt?: UpdatedAt;
}
export interface WorkSubject {
  work?: Work;
  tx?: Transaction;
  deliverables?: Deliverables;
  client?: Client;
  [k: string]: unknown;
}
export interface Work {
  id: string;
  value?: Value;
  tax?: Value1;
  summary: Summary;
  detail?: Detail;
  genre?: Genre;
  tags?: Tags;
  jobType?: JobType;
  startTimestamp?: StartTimestamp;
  endTimestamp?: EndTimestamp;
  platform?: Platform;
  deliverableHash?: DeliverableHash;
  issuedAt: IssuedAt;
  organization?: Organization;
  [k: string]: unknown;
}
export interface Transaction {
  txHash: TxHash;
  to?: To;
  from?: From;
  isPayer?: IsPayer;
  value?: Value2;
  tokenSymbol?: TokenSymbol;
  tokenDecimal?: TokenDecimal;
  fiatValue?: Value3;
  fiatSymbol?: FiatSymbol;
  networkId?: NetworkId;
  issuedTimestamp?: IssuedTimestamp;
  relatedAddresses?: RelatedAddress;
  relatedTxHashes?: RelatedTxHashes;
}
export interface DeliverableItem {
  format?: Format;
  value?: Value4;
}
export interface Client {
  format?: Format1;
  value?: Value5;
  [k: string]: unknown;
}
export interface Signatures {
  holderSig?: HolderSig;
  partnerSigner?: PartnerSigner;
  partnerSig?: PartnerSig;
  agentSigner?: AgentSigner;
  agentSig?: AgentSig;
}
